baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MyConf'

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"

[params]
  themeVariant = "relearn-dark"
  disableLandingPageButton = true
  breadcrumbSeparator = ">"
  editURL = ""
  showVisitedLinks = true
  disableAsideToc = false

  [params.search]
    disable = false

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
